version: "2"
run:
  allow-parallel-runners: true
linters:
  default: all
  disable:
    - depguard
    - err113
#    - exhaustruct
    - godox
    - lll
    - nlreturn
    - nolintlint
    - paralleltest
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl

  settings:
    exhaustruct:
     include:
        - github.com/decisiveai/mdai-gateway/internal/
    revive:
      directives:
        - name: specify-disable-reason
          severity: error
      enable-all-rules: true
      rules:
        - name: add-constant
          severity: warning
          disabled: false
          exclude: [ "" ]
          arguments:
            - max-lit-count: "3"
              allow-strs: '""'
              allow-ints: "0,1,2"
              allow-floats: "0.0,0.,1.0,1.,2.0,2."
        - name: line-length-limit
          disabled: true
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
        - name: var-naming
          severity: warning
          disabled: false
          exclude: [""]
          arguments:
            - ["ID", "Uuid", "Url"] # AllowList
            - ["VM"] # DenyList
            - - upper-case-const: true
    forbidigo:
      forbid:
        - pattern: ^print(ln)?$
          msg: do not commit print statements
        - pattern: ^fmt\.Print.*$
          msg: Do not commit print statements.
        - pattern: log.Fatal
          msg: use zap.L().Fatal instead
        - pattern: ^os.Exit$
          msg: return errors and exit from main()
        - pattern: zap.Any
          msg: define a MarshalLogObject
    depguard:
      rules:
        main:
          list-mode: lax
          deny:
            - pkg: "math/rand$"
              desc: use math/rand/v2
            - pkg: "github.com/sirupsen/logrus"
              desc: use zap
            - pkg: "github.com/pkg/errors"
              desc: should be replaced by standard lib errors package
            - pkg: "io/ioutil"
              desc: deprecated
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        path: internal/*
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports

