apiVersion: v1
kind: Service
metadata:
  name: {{ .AppName }}-envoy-service
  labels:
    app: {{ .AppName }}-envoy
    app.kubernetes.io/instance: {{ .AppName }}-envoy
  {{- if .IsArgoSideload }}
  annotations:
    argocd.argoproj.io/tracking-id: {{ .AppName }}:/Service:mdai/{{ .AppName }}-envoy-service
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 8126
      targetPort: 8126
      protocol: TCP
      name: http
  selector:
    app: {{ .AppName }}-envoy