apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .AppName }}-envoy-config
  labels:
    app.kubernetes.io/instance: {{ .AppName }}-envoy-config
  {{- if .IsArgoSideload }}
  annotations:
    argocd.argoproj.io/tracking-id: {{ .AppName }}:/ConfigMap:mdai/{{ .AppName }}-envoy-config
  {{- end }}
data:
  envoy.yaml: |
    static_resources:
      listeners:
      - name: listener_0
        address:
          socket_address: { address: 0.0.0.0, port_value: 8126 }
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: telemetry_service
                  domains: ["*"]
                  routes:
                  - match: { prefix: "/" }
                    route:
                      cluster: primary_collector
                      request_mirror_policies:
                      - cluster: shadow_collector
                        # runtime_fraction:
                        #   default_value:
                        #     numerator:
                        #     denominator: HUNDRED
              http_filters:
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

      clusters:
        - name: primary_collector
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: primary_collector
            endpoints:
            - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: {{ .AppName }}-primary-collector
                      port_value: 8126

        - name: shadow_collector
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: shadow_collector
            endpoints:
            - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: {{ .AppName }}-shadow-collector
                      port_value: 8126