apiVersion: v1
kind: Secret
metadata:
  name: {{ .AppName }}-integration-secret
  labels:
    app: {{ .AppName }}-integration-secret
    app.kubernetes.io/instance: {{ .AppName }}-integration-secret
  annotations:
    argocd.argoproj.io/tracking-id: {{ .AppName }}:/Secret:mdai/{{ .AppName }}-integration-secret
type: Opaque
stringData:
  api-key: {{ .TempDDAPIKey }}
  site-url: {{ .TempDDURL }}