apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.deployment.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: {{ .Values.deployment.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        envFrom:
          - secretRef:
              name: valkey-secret
        env:
        - name: HTTP_PORT
          value: {{ .Values.service.port }}
        - name: VALKEY_AUDIT_STREAM_EXPIRY_MS
          value: "{{ .Values.auditStreamExpiryMs }}"