apiVersion: v1
kind: Service
metadata:
  name: event-handler-webservice
  namespace: mdai
spec:
  selector:
    app: event-handler-webservice
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: LoadBalancer
